<a href="https://colab.research.google.com/github/ksb7762-k/Codeit-DeepLearning/blob/main/03.TensorFlow_%EA%B8%B0%EC%B4%881.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

tensor란 다차원 배열,
0차원 텐서 스칼라
1차원 텐서 벡터
2차원 센터 행렬
딥러닝에서 사용되는 입력과 출력 그리고 파라미터느 모두 텐서로 표현됨


딥러닝 모델은 결구 ㅅ텐서간의 연산이기 덈누에 테서라는 이름을 갖게 됨
텐서플로에서 텐서를 어떻게 만드든지 알아보자

In [1]:
import tensorflow as tf

In [2]:
tensor = tf.constant([1,2]) # constant함수를 사용해서 텐서를 만들자
tensor

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([1, 2], dtype=int32)>

In [3]:
print(f'data type: {tensor.dtype}')
print(f'number of dimensions: {tensor.ndim}')
print(f'shape: {tensor.shape}')

data type: <dtype: 'int32'>
number of dimensions: 1
shape: (2,)


In [5]:
tensor = tf.constant([1,1.5])
tensor.dtype

tf.float32

In [8]:
tensor = tf.constant([1,2], dtype=tf.float16)
tensor.dtype

tf.float16

In [9]:
import numpy as np

tensor = tf.constant(
    np.array([[1,2], [3,4]])
)

tensor

<tf.Tensor: shape=(2, 2), dtype=int64, numpy=
array([[1, 2],
       [3, 4]])>

지금까지는 텐서를 constant함수로 만들었는데 이름에서 알 수 있듯이 constant함수로 텐서를 만들면 텐서의 값을 바꿀 수 없음  

그런데 학습하는 동안 모델의 파라미터 즉,  웨이트나 바이어스는 경사하강법을 통해 계속 바뀌게 됨  
 =>  변수텐서가 필요하고 variable 객체를 사용함

In [10]:
variable_tensor = tf.Variable([1,2])
variable_tensor

<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([1, 2], dtype=int32)>

In [11]:
variable_tensor = tf.Variable(
    np.array([[1,2], [3,4]])
)
variable_tensor

<tf.Variable 'Variable:0' shape=(2, 2) dtype=int64, numpy=
array([[1, 2],
       [3, 4]])>

shape는 같아야 함

In [14]:
variable_tensor.assign(
    [[4,5], [6,7]]
)
variable_tensor

<tf.Variable 'Variable:0' shape=(2, 2) dtype=int64, numpy=
array([[4, 5],
       [6, 7]])>

TensorFlow를 사용하다 보면 특수한 텐서를 만들어야 할 때가 생김  
 예를 들어 모든 값을 랜덤하게 초기화할 수도 있고, 텐서의 모든 값을 0이나 1로 만들 때도 있음  
  이런 경우에 사용할 수 있는 함수를 몇 가지 살펴보자  


# 랜덤한 값으로 만들기

랜덤한 값을 갖는 텐서는 TensorFlow의 random 모듈에 있는 함수로 만들 수 있음  


가장 대표적인 함수는 normal()  

 원하는 shape를 리스트 형태로 입력하면 평균이 0, 표준편차가 1인 표준 정규 분포를 바탕으로 난수 텐서가 만들어짐  


In [15]:
tf.random.normal([1,3])

<tf.Tensor: shape=(1, 3), dtype=float32, numpy=array([[-0.8377392,  1.1610656,  1.3422768]], dtype=float32)>

mean과 stddev 파라미터를 설정해 정규 분포의 평균과 표준편차를 바꿀 수도 있음

In [16]:
tf.random.normal([1,3], mean=3, stddev=2)

<tf.Tensor: shape=(1, 3), dtype=float32, numpy=array([[1.5137224, 2.9526322, 1.9637183]], dtype=float32)>

uniform() 함수에 원하는 shape를 입력하면 0과 1 사이의 균등 분포를 바탕으로 난수 텐서가 만들어짐  


In [17]:
tf.random.uniform([1,3])

<tf.Tensor: shape=(1, 3), dtype=float32, numpy=array([[0.6096866, 0.6981033, 0.6942154]], dtype=float32)>

minval과 maxval 파라미터를 설정해 균등 분포의 범위를 바꾸는 것도 가능  

 아래처럼 코드를 작성하면 -3과 3 사이의 균등 분포에서 숫자를 뽑아 텐서를 만듬  


In [20]:
tf.random.uniform([1,3], minval = -3, maxval=3)

<tf.Tensor: shape=(1, 3), dtype=float32, numpy=array([[-0.6380367 ,  0.12708378,  1.6469564 ]], dtype=float32)>

# 특정한 값으로 만들기  


ones() 함수에 원하는 shape를 입력하면 값이 전부 1인 텐서를 만들 수 있음

In [21]:
tf.ones([1,3])

<tf.Tensor: shape=(1, 3), dtype=float32, numpy=array([[1., 1., 1.]], dtype=float32)>

한편 zeros() 함수로는 값이 전부 0인 텐서를 만들 수 있음

In [23]:
tf.zeros([1, 3])

<tf.Tensor: shape=(1, 3), dtype=float32, numpy=array([[0., 0., 0.]], dtype=float32)>